name: Lint & Test All Commits
on: push

# Hey, if you're reading this, why not add caching (for literally no reason)??

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Install ktlint"
        uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '1.6.0'

      - name: "Run Lint"
        run: ./gradlew ktlintCheck

  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: "Run Tests"
        run: ./gradlew test
